### PR TITLE
Fix #8 for influx v2

### LINKED ISSUE #8: Influxdb v2: Wrong settings for volume mount and WebGUI (:latest docker container)
Hi,
please check. 
I think these settings should be corrected for influx v2 (this is now :latest version of docker container):
- correct container path is now: /var/lib/influxdb2    (2 is added at the end of path)
- webUI should redirect to port 8086 for influx administration UI. example: http://someIP:8086
Best regards.

### PR DESCRIPTION
**Pull request by simonsickle**
Also update xml to unraid newer format

### CODE REVIEW

**Comment by simonsickle** [comment]
Fixes #8

**Comment by simonsickle** [comment]
On second thought, maybe this should become influx2 template and we should create another to do influx1 for people that want to keep using that? Thoughts @atribe

**Comment by atribemc** [comment]
Yeah, that seems like a good idea since they are so different.

**Comment by simonsickle** [comment]
I'll take that on tonight and update this PR. Would you like to maintain influx 1, 2 or both (template wise)? If you don't want 1 or don't want 2 I can put it in my repository too.

**Comment by atribemc** [comment]
i don't care. you can take it on

**Comment by simonsickle** [comment]
I created 2 new templates (one for influx1 and one for influx2) - I have also asked Squidly what the preferred way is to handle depreciating this template. Depending on that conversation, this PR will get updated https://forums.unraid.net/topic/38619-docker-template-xml-schema/page/6/#comment-1155011

**Pull request closed without merging**
